/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PostgreSqlRecord } from "./PostgreSqlRecord";
import { PostgreSqlRecordCountArgs } from "./PostgreSqlRecordCountArgs";
import { PostgreSqlRecordFindManyArgs } from "./PostgreSqlRecordFindManyArgs";
import { PostgreSqlRecordFindUniqueArgs } from "./PostgreSqlRecordFindUniqueArgs";
import { DeletePostgreSqlRecordArgs } from "./DeletePostgreSqlRecordArgs";
import { PostgreSqlRecordService } from "../postgreSqlRecord.service";
@graphql.Resolver(() => PostgreSqlRecord)
export class PostgreSqlRecordResolverBase {
  constructor(protected readonly service: PostgreSqlRecordService) {}

  async _postgreSqlRecordsMeta(
    @graphql.Args() args: PostgreSqlRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PostgreSqlRecord])
  async postgreSqlRecords(
    @graphql.Args() args: PostgreSqlRecordFindManyArgs
  ): Promise<PostgreSqlRecord[]> {
    return this.service.postgreSqlRecords(args);
  }

  @graphql.Query(() => PostgreSqlRecord, { nullable: true })
  async postgreSqlRecord(
    @graphql.Args() args: PostgreSqlRecordFindUniqueArgs
  ): Promise<PostgreSqlRecord | null> {
    const result = await this.service.postgreSqlRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PostgreSqlRecord)
  async deletePostgreSqlRecord(
    @graphql.Args() args: DeletePostgreSqlRecordArgs
  ): Promise<PostgreSqlRecord | null> {
    try {
      return await this.service.deletePostgreSqlRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
